global:
  edition: ce
  hosts:
    domain: minikube.local
    externalIP: 192.168.49.2  # Replace with the output of `minikube ip`
certmanager:
  install: false
certmanager-issuer:
  email: admin@example.com

nginx-ingress:
  enabled: true
  controller:
    service:
      type: NodePort
